<?php

require_once 'src/Donkey.php';

/**
 * Test class for Donkey.
 * Generated by PHPUnit on 2012-05-18 at 11:50:41.
 */
class DonkeyTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Donkey
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Donkey;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testFoo()
    {
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
